management:
  endpoints:
    web:
      base-path: /my-actuator
      exposure:
        include: "*"
  endpoint:
    shutdown:
      ## 启用快速停服
      enabled: true
eureka:
  instance:
    appname: shutdown-test
  client:
    service-url:
      defaultZone: http://sxli:sxli@localhost:8761/eureka/
